// Generated by CoffeeScript 1.6.2
(function() {
  var login, main, token;

  token = "";

  login = function() {
    var login_template;
    login_template = _.template($('#login-form').html());
    $('.login').append(login_template());
    return $("input.btn.btn-primary").click(function(evt) {
      evt.preventDefault();
      return $.ajax({
        url: 'http://127.0.0.1:3000/api/v1/tokens.json',
        type: "POST",
        dataType: "json",
        data: {
          email: $('input.email').val(),
          password: $('input.password').val()
        },
        success: function(data, status, response) {
          console.log(data, status, response);
          token(data.token);
          return $('.token').append(data.token);
        }
      });
    });
  };

  main = function() {
    return login();
  };

  $(window).load(main);

}).call(this);
