// Generated by CoffeeScript 1.6.2
(function() {
  var NavigationView, login, main, token;

  token = "";

  login = function() {
    var login_template;
    login_template = _.template($('#login-form').html());
    $('.main').empty().append(login_template());
    return $("input.btn.btn-primary").click(function(evt) {
      evt.preventDefault();
      return $.ajax({
        url: 'http://127.0.0.1:3000/api/v1/tokens.json',
        type: "POST",
        dataType: "json",
        data: {
          email: $('input.email').val(),
          password: $('input.password').val()
        },
        success: function(data, status, response) {
          console.log(data, status, response);
          token = data.token;
          return $('.main').empty().append(data.token);
        }
      });
    });
  };

  main = function() {
    var navigateview;
    return navigateview = new NavigationView();
  };

  NavigationView = Backbone.View.extend({
    template: _.template($('#joinview').html()),
    initialize: function() {
      _.bindAll(this);
      this.render();
      return console.log("initialize");
    },
    events: {
      "click #help": "help",
      "click #workspace": "workspace",
      "click #setting": "setting",
      "click #publish": "publish",
      "click #logout": "logout"
    },
    help: function(ev) {
      ev.preventDefault();
      return console.log("HELP", ev.target, $(ev.target).attr('id'));
    },
    workspace: function(ev) {
      return console.log("workspace", ev.target, $(ev.target).attr('id'));
    },
    setting: function(ev) {
      return console.log("setting", ev.target, $(ev.target).attr('id'));
    },
    publish: function(ev) {
      return console.log("publish", ev.target, $(ev.target).attr('id'));
    },
    logout: function(ev) {
      return console.log("logout", ev.target, $(ev.target).attr('id'));
    },
    render: function() {
      this.$el.html(this.template());
      return $('.navigation').empty().append(this.el);
    }
  });

  $(window).load(main);

}).call(this);
