// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  console.log("load background");

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    return console.log(request);
  });

}).call(this);
