// Generated by CoffeeScript 1.6.2
(function() {
  var stored,
    _this = this;

  console.log("load background");

  stored = [];

  chrome.storage.sync.get('tasks', function(storage) {
    console.log("get tasks", storage);
    if (storage.tasks != null) {
      stored = JSON.parse(storage.tasks);
      return console.log("get length", stored.length);
    }
  });

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    console.log(request, JSON.stringify(request));
    if (request.action === "task") {
      return chrome.storage.sync.get('tasks', function(storage) {
        console.log("get tasks", storage);
        if (storage.tasks != null) {
          stored = JSON.parse(storage.tasks);
          console.log("get length", stored.length);
        }
        stored.push(request);
        console.log(JSON.stringify(stored));
        return chrome.storage.sync.set({
          'tasks': JSON.stringify(stored)
        }, function() {
          return console.log('Settings saved');
        });
      });
    }
  });

}).call(this);
