// Generated by CoffeeScript 1.6.2
(function() {
  var click,
    _this = this;

  console.log("page load");

  click = function(e) {
    e.preventDefault();
    console.log("click", e.target, $(e.target)[0].outerHTML);
    return chrome.extension.sendMessage({
      action: "task",
      object: $(e.target)[0].outerHTML
    });
  };

  $("body").on("click", click);

}).call(this);
